services:
  - type: web
    name: battleship-socket-server
    runtime: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
